/**
 * C#/ASP.NET Core project scaffold generator
 * TODO: When extracting to library, this becomes a standalone package
 */

import { ScaffoldGenerator, ScaffoldConfig, ScaffoldResult, GeneratedFile } from '../types'

export class CSharpScaffoldGenerator implements ScaffoldGenerator {
  async generate(config: ScaffoldConfig): Promise<ScaffoldResult> {
    const files: GeneratedFile[] = []

    // Project file
    files.push({
      path: `${config.projectName}.csproj`,
      content: this.generateCsProj(config.projectName),
    })

    // Program.cs
    files.push({
      path: 'Program.cs',
      content: this.generateProgram(),
    })

    // README
    files.push({
      path: 'README.md',
      content: this.generateReadme(config.projectName, config.opportunityContent),
    })

    // Git ignore
    files.push({
      path: '.gitignore',
      content: this.generateGitignore(),
    })

    return {
      files,
      message: `Successfully scaffolded C#/ASP.NET Core project: ${config.projectName}`,
    }
  }

  private generateCsProj(projectName: string): string {
    return `<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>${projectName.replace(/-/g, '_')}</RootNamespace>
  </PropertyGroup>
</Project>
`
  }

  private generateProgram(): string {
    return `var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddRazorPages();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseRouting();
app.UseAuthorization();
app.MapRazorPages();

app.Run();
`
  }

  private generateReadme(projectName: string, opportunityContent?: string): string {
    let readme = `# ${projectName}

This is a Code Lab project generated with Code Labs Generator.

## Getting Started

First, restore dependencies:

\`\`\`bash
dotnet restore
\`\`\`

Then, run the development server:

\`\`\`bash
dotnet run
\`\`\`

Open [https://localhost:5001](https://localhost:5001) with your browser to see the result.

## Learn More

This project was scaffolded as part of a Code Lab learning experience.
`

    if (opportunityContent) {
      readme += `\n## Learning Objectives\n\nThis Code Lab covers:\n\n${opportunityContent.substring(0, 500)}...\n`
    }

    return readme
  }

  private generateGitignore(): string {
    return `## Ignore Visual Studio temporary files, build results, and
## files generated by popular Visual Studio add-ons.

# User-specific files
*.suo
*.user
*.userosscache
*.sln.docstates

# Build results
[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
x64/
x86/
build/
bld/
[Bb]in/
[Oo]bj/

# Visual Studio cache/options directory
.vs/

# .NET Core
project.lock.json
project.fragment.lock.json
artifacts/
`
  }
}
